apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gowiki-azfile-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 100Mi